services:
  db:
    image: postgres:13-alpine
    container_name: db-node-apps
    restart: unless-stopped
    environment:
      POSTGRES_USER: iniuser
      POSTGRES_PASSWORD: inipassword
      POSTGRES_DB: node_apps
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      node-apps-network:
        ipv4_address: 172.31.0.11

volumes:
  postgres_data:

networks:
  node-apps-network:
    name: node-apps-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1